// <auto-generated />
namespace PBL2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Venda_Movel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Venda_Movel));
        
        string IMigrationMetadata.Id
        {
            get { return "201904042227018_[Venda_Movel]"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
