// <auto-generated />
namespace PBL2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class caralho_denovoisso : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(caralho_denovoisso));
        
        string IMigrationMetadata.Id
        {
            get { return "201904042339171_[caralho_denovoisso]"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
